### ISSUE TITLE
Kickoff Meeting Agenda (23rd July 2015, 16:00-17:00 BST)

### ISSUE THREAD

**Issue by hhellyer** [nodejs/post-mortem#1]
The initial agenda will be:
1. Governance - review boilerplates and agree/disagree to use for this project
   - https://github.com/nodejs/post-mortem/blob/master/CONTRIBUTING-draft.md
   - https://github.com/nodejs/post-mortem/blob/master/GOVERNANCE-draft.md
2. Discuss/Confirm scope we want to tackle
   - Define end goals, initial ideas include:
     - Defining and adding interfaces/APIs in order to allow dumps to be generated when needed
     - Defining use cases for post mortem analysis (general debugging, memory analysis)
     - Defining and adding common structures to the dumps generated in order to support tools that want to introspect those dumps
3. Identify initial next steps

**Comment by hhellyer** [comment]
Agenda added to repo here: https://github.com/nodejs/post-mortem/blob/master/meetings/next_agenda.md
Doodle poll for meeting time created here: http://doodle.com/fkranzakx4ikfexi

(Referencing initial members to notify them: @davepacheco @misterdjules @mhdawson @seabaylea @bmeck @danielkhan )

**Comment by davepacheco** [comment]
I think @jclulow is also interested in this topic.  Is it possible to include him?

**Comment by davepacheco** [comment]
Thanks for setting this up.  For reference, I've just finished setting up a new repo for mdb_v8.  The README explains a lot of background on our use of postmortem debugging for Node at Joyent:
https://github.com/joyent/mdb_v8

**Comment by hhellyer** [comment]
@davepacheco @jclulow 
I'm happy for anyone interested to join. The doodle poll should be open to everyone.

I'm not sure how many members we have who aren't IBM or Joyent so we might hit the limits for members from each organisation in https://github.com/nodejs/post-mortem/blob/master/GOVERNANCE-draft.md

**Comment by mhdawson** [comment]
I think the limits likely apply to voting members.  In my opinion anybody who wants to contribute should be welcome.

**Comment by seabaylea** [comment]
I've added @jclulow to the list of initial group members.

**Comment by hhellyer** [comment]
There doesn't seem to be a timeslot suitable for @danielkhan and @davepacheco . I'm going to suggest we go with Thursday 16:00-17:00 (BST) Dave is 8 hours behind as any earlier in the day will probably not be practical.
I'll update the agenda with a meeting time. (I'm not sure yet if I can create a google hangout ahead of the meeting time and publish a URL or not.)

**Comment by danielkhan** [comment]
No problem - it's a busy week for me.

**Comment by davepacheco** [comment]
Apologies for the difficulties in scheduling.  This week is especially tough because I'm on call for jury duty, and so I may not even be able to make the Thursday time slot after all.  I'll confirm as soon as I know, and sorry again for the trouble.

**Comment by hhellyer** [comment]
I've created a google hangout to use: https://plus.google.com/events/cigv4p1lpgudt2f91j9o03stvo8

Myself or Chris will take minutes during the meeting but the hangout _should_ record the meeting so we can make sure they are correct later. I'll aim to post the minutes in the git repository within 24 hours of the meeting.

**Comment by mhdawson** [comment]
I won't be able to make the Thursday timeslot

**Comment by davepacheco** [comment]
Sorry for the doubt.  I'll be able to make the meeting.

**Comment by bmeck** [comment]
need the actual hangout link not the event link if we want to be able to
speak

**Comment by hhellyer** [comment]
https://plus.google.com/hangouts/_/hoaevent/AP36tYeLXt5B8CsEtBFyUJN3RTfRXNaUb3tlKBhm0Z7Y5Gy5FfuEUA
