### ISSUE TITLE
include v8dbg_ symbols in the windows build

### ISSUE THREAD

**Issue by kexuelou** [nodejs/post-mortem#22]
Hey Guys,
mdb_v8 is really great help for production debugging. I would like make it works with Windbg. I tried for some while already, but I failed to find the v8dbvg_\* symbols in my windows node build.

I tried the v8_postmortem_support%': 'true' switch in V8, but make no difference. Thanks in advance.

Regards,
Wei

**Comment by davepacheco** [comment]
This issue probably belongs in nodejs/node repo.  This repo is just for the working group.

In my experience, it's tricky to set GYP variables and have them be propagated correctly.  If you tried setting this in Node's common.gypi, I would try to verify that it was correctly propagated to V8's build.

There's no reason I know of that this would not work.

**Comment by kexuelou** [comment]
Thanks Dave, I tried to build V8 directly with the flag set to true, but didn't work as well.

**Comment by davepacheco** [comment]
How did you set the flag, and how are you verifying whether it worked?

**Comment by richardlau** [comment]
Tidying up post-mortem issues. This was raised in the core repo (https://github.com/nodejs/node/issues/5839) and any follow up should happen there.
