### ISSUE TITLE
Next WG Meeting

### ISSUE THREAD

**Issue by yunong** [nodejs/post-mortem#23]
@nodejs/post-mortem Please participate in this doodle poll for the next meeting: 

http://doodle.com/poll/gsimt9iaii2uphxa

**Comment by indutny** [comment]
Commented!

**Comment by yunong** [comment]
Thanks everyone for participating. Looks like the time that works for the most people will be Monday, April 18, at 10 am PDT. Please put this date in your calendars.

I'll update this with a hangouts link closer to the date.

**Comment by yunong** [comment]
Link for the hangouts is here: https://plus.google.com/events/c3mieb1rlf1f8tgrntcu5qgfmt0

I'll see everyone tomorrow at 10:00 AM PDT

**Comment by yunong** [comment]
Could everyone please comment with an email I can invite to the hangouts?

**Comment by yunong** [comment]
Hangouts link:
https://hangouts.google.com/call/ctxojwwmwnhkjkjzh5mcuzujyue

**Comment by yunong** [comment]
Meeting notes here: https://docs.google.com/document/d/1eC0_hWoe_KY-iNI0xUvAMDoeVZrCd4x4HlyMULhmwJc/edit?usp=sharing

Video here: https://www.youtube.com/watch?v=L9elQyCfRrU
