### ISSUE TITLE
Runtime frame inspection

### ISSUE THREAD

**Issue by coryvirok** [nodejs/post-mortem#25]
I'm looking into providing runtime inspection of Javascript frame information to Javascript code.

If this isn't the right place for this please redirect. Thanks in advance!

I'd like to implement a Node addon which provides detailed inspection of the current call stack of a Javascript program. Something similar to Python's [inspect](https://docs.python.org/2/library/inspect.html) package. 

Specifically, I'd like to be able to access this frame information, (calling function scope/variables/etc.) from a caught exception. I've done an initial investigation into v8 and Node to see if something like this exists but haven't found anything yet. I think I can implement an addon which provides frame inspection for the current frame, but I haven't been able to determine if this is possible during the bubbling phase of an exception. It seems like the addon would need to be able to hook into the initial exception creation to grab a reference to the function's `Isolate` object at the time the exception was thrown.
- Does something like this already exist?
- Is this possible within a Node addon?

Any guidance on this is much appreciated.

Thanks!

**Comment by bnoordhuis** [comment]
You can and you don't even need to write C++ code:

``` js
'use strict';
const Debug = require('vm').runInDebugContext('Debug');
Debug.setListener(function(evt, state, info, unused) {
  if (evt !== Debug.DebugEvent.Exception) return;
  const frame = state.frame(0);
  console.log(state.frameCount(), frame);
  for (let i = 0; i < frame.argumentCount(); ++i)
    console.log(frame.argumentName(i), frame.argumentValue(i));
  for (let i = 0; i < frame.localCount(); ++i)
    console.log(frame.localName(i), frame.localValue(i));
});
Debug.setBreakOnException();
Debug.setBreakOnUncaughtException();  // Not strictly needed in node.js.
function f(x, g) {
  const z = g(x);
  try { throw Error(); } catch (e) {}
}
f(42, Math.sin);
```

Output:

```
10 FrameMirror {
  type_: 'frame',
  break_id_: 2,
  index_: 0,
  details_: 
   FrameDetails {
     break_id_: 2,
     details_: 
      [ 145613372,
        undefined,
        [Function: f],
        2,
        1,
        681,
        false,
        false,
        0,
        'x',
        42,
        'g',
        [Function: sin],
        'z',
        -0.9165215479156338 ] } }
x NumberMirror { type_: 'number', value_: 42, handle_: 10 }
g FunctionMirror {
  type_: 'function',
  value_: [Function: sin],
  handle_: 11,
  resolved_: true }
z NumberMirror { type_: 'number', value_: -0.9165215479156338, handle_: 12 }
```

Look at `deps/v8/src/debug/mirror.js` for the different kinds of value mirrors that exist.

>  I haven't been able to determine if this is possible during the bubbling phase of an exception.

The way I implemented it in strong-agent's function tracer is to break on exceptions, then step until the catch/finally block.  In node.js, there is always a try/catch at the bottom of the JS stack so no special provisions were needed for uncaught exceptions.

Keep in mind that the debugger deoptimizes functions that you inspect or step through so there is a performance hit.

Another thing to note is that the debugger has some quirks where it won't always step correctly through some language constructs and they tend to change over time as bugs get fixed and introduced.  YMMV.

> Does something like this already exist?

I'm fairly sure node-inspector and `node debug` support breaking on exceptions, so yes.

**Comment by coryvirok** [comment]
This is amazing! Thanks for the detailed reply.
