### ISSUE TITLE
Agreeing on semantics of `extra_accessors` in `gen-postmortem-metadata.py`

### ISSUE THREAD

**Issue by misterdjules** [nodejs/post-mortem#27]
The `gen-postmortem-metadata.py` script has [a separate section to define extra accessors](https://github.com/nodejs/node/blob/master/deps/v8/tools/gen-postmortem-metadata.py#L189). These accessors are meant to be defined when accessors for V8 internal objects' properties are not defined in V8's source, but post-mortem debugging tools need to access that data, so they need to know:
- the type of the property
- the offset from the base address of the object

For instance, the [`SeqTwoByteString`](https://github.com/nodejs/node/blob/master/deps/v8/src/objects.h#L9145-L9180) class [stores its characters at offset `kHeaderSize` from its base address](https://github.com/nodejs/node/blob/master/deps/v8/src/objects-inl.h#L3575), but in V8's source it doesn't define an accessor with the `DECL_ACCESSORS` macro. As a result, [an extra accessor](https://github.com/nodejs/node/blob/master/deps/v8/tools/gen-postmortem-metadata.py#L220) is defined in `gen-postmortem-metadata.py` for this property.

These accessors are meant to define offsets from which to compute addresses for properties of objects stored in V8's heap. Now, heap object pointers are "tagged" by having the last bit set, but heap objects are also always 4-bytes aligned, so when computing these addresses, the least significant bit needs to be cleared.

This is [what mdb_v8 does](https://github.com/joyent/mdb_v8/blob/master/src/mdb_v8.c#L1501) when computing the offset of a property from a base address.

However, recently some constants that are not offsets have been added to that section. For instance, [indices of slots within a function "context" have been added as extra accessors](https://github.com/nodejs/node/blob/master/deps/v8/tools/gen-postmortem-metadata.py#L191-L194). One of these values, `NATIVE_CONTEXT_INDEX`, is currently equal to `3`, and thus has the last bit set.

When loading these values with `mdb_v8`, as we described previously, we clear the last bit and we end up loading the value for `NATIVE_CONTEXT_INDEX` as 2 instead of 3. This breaks mdb_v8 because it assumed that the constants defined in that section could be safely considered as offsets to V8 heap objects' properties, and thus that it was safe to clear the least significant bit.

Moving the "Context" constants from the `extra_accessors` table to the [`consts_misc` table](https://github.com/nodejs/node/blob/master/deps/v8/tools/gen-postmortem-metadata.py#L55) would solve this problem.

It would be possible to solve this specific problem in mdb_v8 by clearing the least significant bit of the base address instead of clearing the least significant bit of the offset when computing addresses for properties. However, a broader issue is that `extra_accessors` defines offsets to properties and the type of the data of these properties' values.

Using the example of the `SharedFunctionInfo` class, [the extra accessor for the `scope_info` property](https://github.com/nodejs/node/blob/master/deps/v8/tools/gen-postmortem-metadata.py#L222) defines its type being `ScopeInfo`. This helps post-mortem debuggers to know what kind of data to read at that offset.

In the example of [the `Context` offsets](https://github.com/nodejs/node/blob/master/deps/v8/tools/gen-postmortem-metadata.py#L222), these offsets are defined as pointing to data of type `int`, which is actually not true. For instance, the `NATIVE_CONTEXT_INDEX` index in static context slots point to the "native context", which is a `FixedArray` instance.

In my opinion this further shows that some of the offsets defined in the `extra_accessors` table are really constants, and should be defined in the [`consts_misc`](https://github.com/nodejs/node/blob/master/deps/v8/tools/gen-postmortem-metadata.py#L55) table.

So my questions are:
1. Does it make sense for all post-mortem debugging tools implementers to agree on `extra_accessors` defining _only_ offsets to objects' properties that are missing an accessor declaration in V8's code, and _not_ defining other types of constants? I would think so, but I haven't looked at the implementation of other post-mortem debugging tools, so I'd like to get a feeling whether 2) would break some of them.
2. If we agree on 1), are you OK with me submitting a patch to V8 that moves all these constants that are not offsets from the `extra_accessors` table to the `consts_misc` table?

**Comment by davepacheco** [comment]
Sorry for my delay in looking at this.  I think your assessment is correct -- these were always intended to describe offsets into objects whose pointers would be tagged, and I think it would be good to make this consistent.  I'm fine with moving those other constants to the other table.

**Comment by indutny** [comment]
You are absolutely correct @misterdjules, I agree with this. Will patch llnode as soon as the patch will make it to v8's upstream.

Thank you for pinging me!

**Comment by misterdjules** [comment]
@davepacheco @indutny Thank you for the prompt feedback, I'll let you know when the patch is upstreamed.

**Comment by misterdjules** [comment]
@davepacheco @indutny Submitted upstream with https://codereview.chromium.org/2051563003/. I tested mdb_v8 with these changes and all tests pass, and mdb_v8 actually doesn't use some of the constants that were moved  (all the dictionary shape classes' constants).

@indutny Do you mind taking a look at it to make sure this wouldn't break llnode?

Closing this issue as its main goal is already achieved, but feel free to continue the discussion here. Thank you!

**Comment by indutny** [comment]
@misterdjules thank you for the heads up! Landed https://github.com/indutny/llnode/commit/f2e8f46ff089ebc0e4c1f69e554bec0554682abf
