### ISSUE TITLE
Marketing Request

### ISSUE THREAD

**Issue by gtewallace** [nodejs/post-mortem#28]
Apologies in advance if this is the wrong place for this request. I also posted on trace WG.

The Node.js Foundation is putting together a presentation for general use by the community to unequivocally establish Node's place as enterprise-ready. The intended audience is Node.js devs inside enterprises who may not be using Node as much as possible. The preso, ideally, will equip them with the material they need to convince their peers and management.

One of the things still missing is a slide (preferably a single slide, but could be multiple if needed) to summarize the performance/performance tuning/debugging considerations for enterprises running Node.js at scale.

Obviously we're not going to cover the topic in any detail in a single slide. Rather, the goal is to highlight the key elements of the topic and share the tools/resources available and work underway in Core and in the community on the topic.

Is this something this group could help with?

Thanks in advance!

**Comment by misterdjules** [comment]
@gtewallace 

> Is this something this group could help with?

I think we could probably put together a slide that presents post-mortem debugging, but not performance, performance tuning or live debugging. Is there a draft of these slides to get a better feeling of the tone and level of details that would best fit the rest of the presentation?

**Comment by gtewallace** [comment]
@misterdjules thanks!

Here's the link to the current draft: https://docs.google.com/presentation/d/1KdYniohBE_APp8ngD_TTE0-Hl5loxXCTnj1AnEorebc/edit?usp=sharing

See slide 16 - the current content there is draft/placeholder that I pulled from a blog written by @yunong 

I can break it into two parts, with one focused on performance tuning and the second on post mortem.

Thanks again!!

**Comment by lucamaraschi** [comment]
@gtewallace I agree with the point made by @misterdjules but if your target audience is mainly business, I then recommend to change the description into something more understandable by them.
Can we just add comments to that slide or what is the process of contributing?

**Comment by gtewallace** [comment]
@lucamaraschi yes comments in the presentation is perfect 

Ty!

**Comment by misterdjules** [comment]
Added a couple comments in the presentation itself. Let me know if that helps!

**Comment by richardlau** [comment]
Closing as I'm assuming this was done.
