### ISSUE TITLE
Adding David Mark Clements to the WG

### ISSUE THREAD

**Issue by lucamaraschi** [nodejs/post-mortem#29]
Given the involvement and the skills of @davidmarkclements, I suggest to add him to the WG.
He developed libraries like [0x](https://github.com/davidmarkclements/0x) and [autopsy](https://github.com/nearform/autopsy).

**cc:** @davepacheco

**Comment by lucamaraschi** [comment]
@nodejs/post-mortem anybody can add @davidmarkclements to the collaborators of this WG?

**Comment by misterdjules** [comment]
@lucamaraschi I just sent him an invite to be part of the nodejs/post-mortem team, so I'm closing this issue, but feel free to reopen or comment if there's anything else that needs to be done.

**Comment by davidmarkclements** [comment]
thanks @misterdjules !
