### ISSUE TITLE
Repositories to contribute collaboratively

### ISSUE THREAD

**Issue by mhdawson** [nodejs/post-mortem#30]
There are a number of efforts that we have underway were members of the post-mortem WG needs to work together on code for tools/modifications to Node.

This is my starting list of options:
- use a folder under the nodejs/post-mortem repository.  If we want to do that we could just use something like nodejs/post-mortem/tools and create directories as needed under there.
- create additional projects under github/nodejs
- use a new organization (I created node-postmortem just in case).  In this case we can create projects for each effort (ex lldb, NodeReport, portable mdb etc.).  I'd assume we'd use MIT as the licence in those projects to be compatible with Node.  We would make the member of the post-mortem WG owners of that new organization.
- Continue to use personal repositories ex github/indutny/llnode

There has been concern over 1 and 2 in terms of it looking like the Node.js community  be favoring one implementation versus another.

I'd personally be ok with any of 1 through 3 for projects we are actively collaborating but given concern over 1 and 2 then maybe 3 is a reasonable option ?

**Comment by mhdawson** [comment]
@nodejs/post-mortem please comment on where you think we should put code we are collaborating on.

**Comment by davepacheco** [comment]
I suspect this may depend on the subproject.  For example, work on a portable mdb_v8 should probably live with the existing mdb_v8 project.  I don't think there's a need to consolidate these projects into one place, but I do think it would be worthwhile to provide a central place to link to these other projects.

**Comment by indutny** [comment]
I'm 👍 for separate repos in `nodejs` organization. This way it is simpler to cc other wgs.

**Comment by rnchamberlain** [comment]
Also +1 for repos under github/nodejs. Specifically to have mdb_v8 and llnode move there - as the key core-dump analysis projects.

**Comment by davepacheco** [comment]
Frankly, I really don't want to move mdb_v8.  We've got a bunch of state around the repo, links to it from different places, and it's already hard enough to dig through its source history, owing to its moving between several repos in the past.  (This is documented in the changelog.)  And there's no stated purpose here.

Which other projects are we talking about?  Would the IDDE support for Node core dump debugging move under the new org?

**Comment by mhdawson** [comment]
I don't think we need to move everything but I would like a place were this group can collaborate without using personal repositories or having to pick one company's repo.  In the case where there is an existing project with existing history/home it can stay there but for other newer projects like llnode and NodeReport I do think projects either under github/nodejs or github/node-postmortem makes sense (I'm happy with either).

**Comment by indutny** [comment]
I'll be happy to move `llnode` to nodejs org.

@davepacheco there is no need to erase repo history or to break anything for anyone. Github supports transfers between organizations and old `git@...` urls will still work. However, I completely understand if you don't want to move the repo.

To me it is just a way to gather more collaboration momentum.

**Comment by mhdawson** [comment]
Good discussion in the last post-mortem WG meeting.  There was no objection to projects like lldb/NodeReport going under github/nodejs and generally and it is the preferred option when it does not make more sense to have the project somewhere else.   To summarize:
- Not all projects being working on by this group would necessarily be moved to github/nodejs.  Only where it makes sense for the project.
- Where it makes sense to the project there is no object from the participants for projects going under github/nodejs.
- We'll ask the CTC for the ok to move llnode https://github.com/indutny/llnode to github/node.js and to create a new github.com/NodeReport project.

Michael took action to add to ctc agenda.

**Comment by mhdawson** [comment]
Adding to CTC agenda, unfortunately I'm going to miss the CTC meeting the week of the 26th so may make sense to discuss the following week.

**Comment by misterdjules** [comment]
@mhdawson Shouldn't this discussion happen in a TSC meeting rather than a CTC meeting?

**Comment by jasnell** [comment]
Switched to TSC agenda.

**Comment by mhdawson** [comment]
Discussion in CTC meeting

1) Free to open new project for NodeReport, (and others in the future) just make sure to include boilerplate governance files, I'll do that early next wee.

2) For llnode general agreement on move.  Process should be:
  a) add boilerplate governance files to existing project
  b) open issue in TSC requesting move, once there are a few LGTMs then move to nodejs org.

**Comment by mhdawson** [comment]
PR to add governance files to new nodejs/nodereport project

https://github.com/nodejs/nodereport/pull/1

@nodejs/post-mortem @nodejs/tsc please review/comment.

**Comment by mhdawson** [comment]
Nodeport has been created under nodejs and we created TSC issue requesting the move. Closing this issue.
