### ISSUE TITLE
NodeSummit WG Meetup 

### ISSUE THREAD

**Issue by yunong** [nodejs/post-mortem#32]
Looks like a bunch of folks are going to be in SF for NodeSummit @lucamaraschi @mhdawson @indutny (Fedor please confirm), in addition to the fact that Joyent and Google folks are local @davepacheco @jclulow, @ofrobots 

This is a good opportunity for us to all meet in person, talk about what everyone's working on. Instead of something formal, let's make this an informal social event. Perhaps dinner and drinks?

Could I get everyone to confirm that they're open to participating? We are able to host down here at Netflix in Los Gatos -- but I'm happy to meet up in San Francisco as well if there's a more easily accessible location.

**Comment by indutny** [comment]
I am not going there, sorry!

**Comment by mhdawson** [comment]
I should be there and would like to participate

**Comment by davepacheco** [comment]
Assuming we're talking about the week of July 27, I should be around.

**Comment by ofrobots** [comment]
I would be around as well and would be interested in participating as long as the logistics don't interfere with the APM summit.

**Comment by yunong** [comment]
From feedback from a bunch of folks, let's make this a more social event -- think of it more as a meetup to get to know each other in person.

**Comment by lucamaraschi** [comment]
@davidmarkclements and I are absolutely in ;-)
Shall we just circle a Doodle to pick a date and time during the week?

**Comment by yunong** [comment]
Tentatively we're looking at Monday, July 25th, sometime in the afternoon/evening. Does this work for everyone? cc/ @nodejs/post-mortem

**Comment by davepacheco** [comment]
Works for me.

**Comment by davidmarkclements** [comment]
yep - looking forward to meeting everyone! 

@lucamaraschi you can too?

**Comment by lucamaraschi** [comment]
Absolutely in!

@yunong any idea of the location?

**Comment by yunong** [comment]
I'll update the issue with a location once i've made reservations. Everyone
should feel free to recommend something.a

**Comment by davepacheco** [comment]
It's a bit of a hike, but we've had good luck getting a table at the Rogue Ale Public House.

**Comment by mhdawson** [comment]
I fly in Sunday so Monday works for me.  I'm staying near the conference so somewhere within walking distance would be nice.

**Comment by yunong** [comment]
I have some good news. Netflix has decided to sponsor the event. The venue will be at http://www.25lusk.com/  25 Lusk St, San Francisco, CA 94107

Stay tuned for the exact time and details. Right now I'm assuming that @davepacheco @jclulow @mhdawson @lucamaraschi @davidmarkclements and myself are attending. Please let me know if any others are around and wish to attend.

**Comment by mcollina** [comment]
I'll be around, if it's not a problem.

**Comment by lucamaraschi** [comment]
@yunong I had to stay landed in Amsterdam due to a terrible flu!I spoke with @mcollina and he will hop by and I can facetime/skype in...

**Comment by yunong** [comment]
@mcollina you're more than welcome to join us.

**Comment by yunong** [comment]
Meetup starts at 6pm -- I'll see everyone there!

**Comment by mhdawson** [comment]
Looking forward to it.

**Comment by yunong** [comment]
When you folks arrive please ask for either the Netflix event or ask for me by name, and they should show you to our reservation.

**Comment by mhdawson** [comment]
Closing as this is done
