### ISSUE TITLE
Next meeting or get together at Node Interactive NA

### ISSUE THREAD

**Issue by mhdawson** [nodejs/post-mortem#38]
Its been a while since we got together.  There has been progress on nodereport and lldb, and I'm thinking we should sync on the other efforts as well. 

Who is going to be at Node Interactive NA

@nodejs/post-mortem

**Comment by sam-github** [comment]
I will be (though I'm not a member of the WG at the moment, I'm an interested observer of nodereport, with plans to use it soon).

**Comment by joshgav** [comment]
I'll be there and would attend too. There may be some benefit to combining with https://github.com/nodejs/summit/issues/30.
