### ISSUE TITLE
Update README.md to reflect goals as discussed in first meeting

### ISSUE THREAD

**Issue by hhellyer** [nodejs/post-mortem#5]
Currently the the description of the working group in README.md says:

"The Post Mortem Diagnostics working group is dedicated to support and improvement of post mortem debugging for Node. It seeks to provide the APIs/tools needed to generate dumps when required and to use these dumps to be able to debug issues."

Based on the discussions in the meeting I propose updating it to: 

"The Post Mortem Diagnostics working group is dedicated to support and improvement of post mortem debugging for Node. It seeks to elevate the role of post mortem debugging for Node.js making techniques and tools known and available to Node.js users."

Please feel free to suggest changes to the wording above. Once we've agreed something we can update it.

**Comment by davepacheco** [comment]
That sounds good.  Here's a nitty revision:

"The Postmortem Diagnostics working group is dedicated to the support and improvement of postmortem debugging for Node.js. It seeks to elevate the role of postmortem debugging for Node, to assist in the development of techniques and tools, and to make techniques and tools known and available to Node.js users."

**Comment by rvagg** [comment]
There's a `@nodejs/post-mortem` team who manages this repo with just two people on it, one of whom is @mikeal who created it, I'd like to put everyone at the bottom of the README onto that team, can someone let me know if that's not appropriate for some reason before I do this?

**Comment by mikeal** [comment]
we should promote someone to team admin so they can add and remove members of the github team as the group evolves.

**Comment by seabaylea** [comment]
I've updated the readme with Dave's revision of Howard's suggested update.

@mhdawson Can you add the other group members to the team?
