### ISSUE TITLE
Next post mortem meeting date and agenda.

### ISSUE THREAD

**Issue by hhellyer** [nodejs/post-mortem#8]
Date: Friday October 9th 2015.
1. Use cases identified in issue #7 
2. Existing tooling identified in issue #6 
3. State of post-mortem debugging tools with node v4.x and upcoming v5.x:
   - joyent/mdb_v8
   - IBM's IDDE
4. # 10: Cross-platform post-mortem debugging tools.
5. Meeting schedule.

Meeting Minutes: https://docs.google.com/document/d/1aF5j-tr4fN9i1D5HKqLeIUpFGTG657veu33aMfzmDFo/edit?usp=sharing

**Comment by yunong** [comment]
Hi, we use post mortem debugging heavily at Netflix. I would love to join and contribute!

**Comment by jclulow** [comment]
+1 to @yunong -- would be great to have the wood of production node debugging experience at Netflix behind this arrow.

**Comment by seabaylea** [comment]
+1. I've added Yunong to the group membership list used for invites.

**Comment by lucamaraschi** [comment]
Is there anything already planned for this meeting?

**Comment by yunong** [comment]
I'd also like to propose we talk about https://github.com/nodejs/node/issues/2764

**Comment by yunong** [comment]
Also, I'd like to propose that @lucamaraschi join this WG, as he has significant working experience with post mortem debugging.

**Comment by misterdjules** [comment]
@nodejs/post-mortem I created a doodle to find a date and time that work for most people interested, please fill it out here: http://doodle.com/poll/ypr7wdgyyg7tix9d.

I haven't been on any previous call, have you had one already? If so, what did you guys use to do a conference call? Google Hangouts, Google Hangouts on Air, uberconference, anything else?

**Comment by davepacheco** [comment]
The next two weeks are pretty tough for me because I'm on travel.  I'm
basically not going to be able to make anything before the 30th.  Sorry.

**Comment by davepacheco** [comment]
I thought we had added all members to the post-mortem team, but I don't see @jclulow on it.  Can someone add him?

**Comment by misterdjules** [comment]
@davepacheco Yes, I invited him to the team, as well as @bmeck, @lucamaraschi and @hhellyeribm.

@jclulow Did you get the invite?

**Comment by misterdjules** [comment]
@davepacheco If we get enough people available next week, we will write (maybe even record) minutes, and there's always the possibility to have follow-up discussions on GitHub in this repository. Would you mind if we still setup a meeting for next week?

**Comment by davepacheco** [comment]
I'd really like to be involved in a potential discussion of making mdb_v8 more broadly available (which yunong mentioned he wants to talk about), and also the various use-cases for postmortem debugging that I added to #7.  But if there's some reason this needs to happen in the next week and a half, I understand.

**Comment by lucamaraschi** [comment]
@misterdjules can we post-pone it till @davepacheco is back?I think his contributions to mdb_v8 are remarkable and he can be an accelerator for the discussion about porting it on other platforms. @yunong agree?

**Comment by misterdjules** [comment]
Sounds good, let's do that when @davepacheco is back :+1: I'll post another doodle shortly.

**Comment by misterdjules** [comment]
Same doodle link: http://doodle.com/poll/ypr7wdgyyg7tix9d. Can you please update your availabilities? Thanks! :)

**Comment by seabaylea** [comment]
Looking at the times in the poll, I'm assuming they're PST? I've filled in my availability assuming they are!

**Comment by misterdjules** [comment]
@seabaylea Yes, times are PST.

**Comment by misterdjules** [comment]
So far the time slot with most people is Friday October 9th at 10pm. However, I don't like that it would leave @seabaylea out. @seabaylea Is there a chance that you could make it at that time?

Also, we haven't heard from @hhellyeribm, @bmeck and @jclulow, please let us know if we can make it work for you.

**Comment by seabaylea** [comment]
I'm potentially travelling that week, but if I am I would expect to be back by 10**am** PST / 6pm UK (just tired!). I'll update the doodle poll to reflect that.

**Comment by misterdjules** [comment]
@seabaylea Excellent, thank you!

**Comment by misterdjules** [comment]
@nodejs/post-mortem I sent an invite for this meeting to people who filled out the doodle. @seabaylea I don't have your email address, can you please send it to me so I can invite you to the meeting?

Also please make sure to mention the topics you'd like to discuss during the meeting in this issue.

Thank you!

**Comment by ofrobots** [comment]
@misterdjules Can you add me to invite as well?

**Comment by misterdjules** [comment]
@ofrobots Done!

**Comment by misterdjules** [comment]
@ofrobots You're not a member of the [post-mortem team](https://github.com/orgs/nodejs/teams/post-mortem) yet, do you want me to add you to it?

**Comment by seabaylea** [comment]
@misterdjules Can you send it to cnbailey at gmail.com?

**Comment by misterdjules** [comment]
@seabaylea Thanks, invitation sent.

**Comment by ofrobots** [comment]
> @ofrobots You're not a member of the post-mortem team yet, do you want me to add you to it?

@misterdjules yes please, Thanks!

**Comment by misterdjules** [comment]
@ofrobots Done.

**Comment by misterdjules** [comment]
Updated the original description to include the actual date of the meeting, as well as additional agenda items. Feel free to update it too with the items you'd like to put on the agenda too.

**Comment by misterdjules** [comment]
@nodejs/post-mortem Just a reminder that the meeting is today at 10:00 AM PDT. Please update the original description of this issue with items you'd like to discuss during the meeting so that we don't have to spend too much time discussing what we want to discuss :)

The link to the Google Hangout is: https://plus.google.com/hangouts/_/nodejs.org/node-postmortem.

Thank you!

**Comment by lucamaraschi** [comment]
@misterdjules shouldn't we start fresh defining what we are looking for and what our goals based on the concrete use cases that we can put on the table? 
I am looking to have a clear baseline for everybody and avoid starting from the tools...does it make any sense?

**Comment by davepacheco** [comment]
@lucamaraschi Is that different than we're doing under #7 (which is agenda item #1)?

**Comment by misterdjules** [comment]
@lucamaraschi As @davepacheco mentions, I think that is covered by the first agenda item.

Some of the other agenda items that I added are not directly related to that, but I still think it would still be  worth it to at least give a quick status update on them.

**Comment by lucamaraschi** [comment]
@davepacheco sorry I lost track of #1...but I think it covers exactly what I meant
